# Generated by Django 5.1.5 on 2025-11-02 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTimeslot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'base_timeslots',
            },
        ),
        migrations.CreateModel(
            name='DailyTimeslot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('title', models.CharField(max_length=80)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='app.basetimeslot')),
            ],
            options={
                'db_table': 'daily_timeslots',
            },
        ),
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('join_date', models.DateField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'), models.Index(fields=['join_date'], name='users_join_da_19a8f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('sinpe', 'SINPE')], max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.gymuser')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='TimeslotSignup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slot_date', models.DateField()),
                ('daily_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.dailytimeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.gymuser')),
            ],
            options={
                'db_table': 'timeslot_signups',
            },
        ),
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='app.gymuser')),
            ],
            options={
                'db_table': 'user_weights',
            },
        ),
        migrations.AddIndex(
            model_name='dailytimeslot',
            index=models.Index(fields=['slot_date'], name='daily_times_slot_da_a065d5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimeslot',
            index=models.Index(fields=['status'], name='daily_times_status_f8009c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailytimeslot',
            constraint=models.UniqueConstraint(fields=('slot_date', 'title'), name='uniq_daily_date_title'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'period_start', 'period_end'], name='idx_pay_user_period'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='payments_paid_at_c989bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gt', models.F('period_start'))), name='payments_period_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='timeslotsignup',
            index=models.Index(fields=['user', 'slot_date'], name='idx_signup_user_date'),
        ),
        migrations.AddConstraint(
            model_name='timeslotsignup',
            constraint=models.UniqueConstraint(fields=('daily_slot', 'user'), name='uniq_signup_slot_user'),
        ),
        migrations.AddConstraint(
            model_name='timeslotsignup',
            constraint=models.UniqueConstraint(fields=('user', 'slot_date'), name='uniq_signup_user_day'),
        ),
        migrations.AddIndex(
            model_name='userweight',
            index=models.Index(fields=['user', 'recorded_at'], name='user_weight_user_id_786d43_idx'),
        ),
    ]
