# Generated by Django 5.0.1 on 2025-11-10 01:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTimeslot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('capacity', models.PositiveIntegerField()),
                ('day_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'base_timeslots',
                'ordering': ['day_order'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gyms',
                'indexes': [models.Index(fields=['is_active'], name='gyms_is_acti_07dba4_idx'), models.Index(fields=['name'], name='gyms_name_4e91a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyTimeslot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('title', models.CharField(max_length=80)),
                ('capacity', models.PositiveIntegerField()),
                ('day_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='app.basetimeslot')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='app.gym')),
            ],
            options={
                'db_table': 'daily_timeslots',
                'ordering': ['day_order'],
            },
        ),
        migrations.AddField(
            model_name='basetimeslot',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_slots', to='app.gym'),
        ),
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('join_date', models.DateField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('height_cm', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.gym')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('sinpe', 'SINPE')], max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.gymuser')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='TimeslotSignup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slot_date', models.DateField()),
                ('daily_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.dailytimeslot')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.gymuser')),
            ],
            options={
                'db_table': 'timeslot_signups',
            },
        ),
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='app.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='app.gymuser')),
            ],
            options={
                'db_table': 'user_weights',
            },
        ),
        migrations.AddIndex(
            model_name='dailytimeslot',
            index=models.Index(fields=['gym', 'slot_date'], name='daily_times_gym_id_fbdaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimeslot',
            index=models.Index(fields=['gym', 'status'], name='daily_times_gym_id_b759a2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimeslot',
            index=models.Index(fields=['day_order'], name='daily_times_day_ord_3a7b4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailytimeslot',
            constraint=models.UniqueConstraint(fields=('gym', 'slot_date', 'title'), name='uniq_daily_date_title_per_gym'),
        ),
        migrations.AddIndex(
            model_name='basetimeslot',
            index=models.Index(fields=['gym', 'is_active'], name='base_timesl_gym_id_b4d252_idx'),
        ),
        migrations.AddIndex(
            model_name='basetimeslot',
            index=models.Index(fields=['day_order'], name='base_timesl_day_ord_a169a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='basetimeslot',
            constraint=models.UniqueConstraint(fields=('gym', 'title'), name='uniq_base_title_per_gym'),
        ),
        migrations.AddIndex(
            model_name='gymuser',
            index=models.Index(fields=['gym', 'is_active'], name='users_gym_id_568227_idx'),
        ),
        migrations.AddIndex(
            model_name='gymuser',
            index=models.Index(fields=['gym', 'join_date'], name='users_gym_id_1f0a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='gymuser',
            index=models.Index(fields=['gym', 'phone'], name='users_gym_id_c238dc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym', 'user', 'period_start', 'period_end'], name='idx_pay_gym_user_period'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym', 'paid_at'], name='payments_gym_id_7758f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gt', models.F('period_start'))), name='payments_period_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='timeslotsignup',
            index=models.Index(fields=['gym', 'user', 'slot_date'], name='idx_signup_gym_user_date'),
        ),
        migrations.AddConstraint(
            model_name='timeslotsignup',
            constraint=models.UniqueConstraint(fields=('daily_slot', 'user'), name='uniq_signup_slot_user'),
        ),
        migrations.AddConstraint(
            model_name='timeslotsignup',
            constraint=models.UniqueConstraint(fields=('gym', 'user', 'slot_date'), name='uniq_signup_user_day_per_gym'),
        ),
        migrations.AddIndex(
            model_name='userweight',
            index=models.Index(fields=['gym', 'user', 'recorded_at'], name='user_weight_gym_id_ff1762_idx'),
        ),
    ]
