# Generated by Django 5.0.1 on 2025-11-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('staff', 'Staff')], default='member', max_length=20),
        ),
    ]
