# Generated by Django 5.0.1 on 2025-12-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gymuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetimeslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytimeslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
