# Generated by Django 5.1.5 on 2025-11-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20251102_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='gymuser',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
    ]
