# Generated by Django 5.0.1 on 2026-01-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_basetimeslot_start_time_dailytimeslot_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('profile_update', 'Actualización de perfil'), ('password_change', 'Cambio de contraseña'), ('group_join', 'Entrada a grupo'), ('group_leave', 'Salida de grupo'), ('member_add', 'Alta de miembro'), ('member_remove', 'Baja de miembro'), ('base_schedule_activate', 'Activar horario base'), ('base_schedule_deactivate', 'Desactivar horario base'), ('payment_add', 'Registro de pago'), ('error', 'Error')], max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='app.gym')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
