# Generated by Django 5.0.1 on 2026-01-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('profile_update', 'Actualización de perfil'), ('password_change', 'Cambio de contraseña'), ('group_join', 'Entrada a grupo'), ('group_leave', 'Salida de grupo'), ('member_add', 'Alta de miembro'), ('member_remove', 'Baja de miembro'), ('base_schedule_activate', 'Activar horario base'), ('base_schedule_deactivate', 'Desactivar horario base'), ('payment_add', 'Registro de pago'), ('payment_remove', 'Eliminacion de pago'), ('error', 'Error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='app.gym'),
        ),
    ]
