# Generated by Django 5.0.1 on 2025-11-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20251102_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='height_cm',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
