# Generated by Django 5.0.1 on 2026-01-26 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_activitylog_event_type_alter_activitylog_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('profile_update', 'Actualización de perfil'), ('password_change', 'Cambio de contraseña'), ('group_join', 'Entrada a grupo'), ('group_leave', 'Salida de grupo'), ('member_add', 'Alta de miembro'), ('member_remove', 'Baja de miembro'), ('couch_add', 'Alta de entrenador'), ('couch_remove', 'Baja de entrenador'), ('base_schedule_activate', 'Activar horario base'), ('base_schedule_deactivate', 'Desactivar horario base'), ('payment_add', 'Registro de pago'), ('payment_remove', 'Eliminacion de pago'), ('error', 'Error')], max_length=50),
        ),
        migrations.CreateModel(
            name='MeasurementDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('unit_type', models.CharField(choices=[('cm', 'Centímetros'), ('kg', 'Kilogramos'), ('percent', 'Porcentaje'), ('text', 'Texto'), ('number', 'Número')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'measurement_definitions',
                'indexes': [models.Index(fields=['is_active'], name='measurement_is_acti_eb8582_idx'), models.Index(fields=['unit_type'], name='measurement_unit_ty_f04503_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeasurementRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_records', to='app.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_records', to='app.gymuser')),
            ],
            options={
                'db_table': 'measurement_records',
            },
        ),
        migrations.CreateModel(
            name='MeasurementValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('definition_code', models.SlugField()),
                ('definition_name', models.CharField(max_length=80)),
                ('unit_type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='app.measurementrecord')),
            ],
            options={
                'db_table': 'measurement_values',
            },
        ),
        migrations.AddIndex(
            model_name='measurementrecord',
            index=models.Index(fields=['gym', 'user', 'record_date'], name='measurement_gym_id_a1d3d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurementrecord',
            constraint=models.UniqueConstraint(fields=('gym', 'user', 'record_date'), name='uniq_measurement_record_user_date'),
        ),
        migrations.AddIndex(
            model_name='measurementvalue',
            index=models.Index(fields=['definition_code'], name='measurement_definit_8054e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurementvalue',
            constraint=models.UniqueConstraint(fields=('record', 'definition_code'), name='uniq_measurement_per_record'),
        ),
    ]
