# Generated by Django 5.0.1 on 2025-11-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gymuser_height_cm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_cents',
            new_name='amount',
        ),
    ]
