# Generated by Django 5.0.1 on 2026-01-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_weight'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measurementvalue',
            name='uniq_measurement_per_record',
        ),
        migrations.RemoveIndex(
            model_name='measurementvalue',
            name='measurement_definit_8054e2_idx',
        ),
        migrations.RemoveField(
            model_name='measurementdefinition',
            name='code',
        ),
        migrations.RemoveField(
            model_name='measurementvalue',
            name='definition_code',
        ),
    ]
