# Generated by Django 5.0.1 on 2026-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_measurementvalue_uniq_measurement_per_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdefinition',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
