# Generated by Django 5.0.1 on 2026-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_measurementdefinition_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementdefinition',
            name='unit_type',
            field=models.CharField(choices=[('cm', 'Centímetros'), ('kg', 'Kilogramos'), ('%', 'Porcentaje'), ('text', 'Texto'), ('#', 'Número')], max_length=20),
        ),
    ]
