# Generated by Django 5.0.1 on 2026-01-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_measurementdefinition_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementvalue',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
