# Generated by Django 5.0.1 on 2025-11-07 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_create_initial_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gyms',
            },
        ),
        migrations.RemoveConstraint(
            model_name='dailytimeslot',
            name='uniq_daily_date_title',
        ),
        migrations.RemoveConstraint(
            model_name='timeslotsignup',
            name='uniq_signup_user_day',
        ),
        migrations.RemoveIndex(
            model_name='dailytimeslot',
            name='daily_times_slot_da_a065d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailytimeslot',
            name='daily_times_status_f8009c_idx',
        ),
        migrations.RemoveIndex(
            model_name='gymuser',
            name='users_is_acti_847b48_idx',
        ),
        migrations.RemoveIndex(
            model_name='gymuser',
            name='users_join_da_19a8f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='gymuser',
            name='users_phone_af6883_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_pay_user_period',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_paid_at_c989bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeslotsignup',
            name='idx_signup_user_date',
        ),
        migrations.RemoveIndex(
            model_name='userweight',
            name='user_weight_user_id_786d43_idx',
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['is_active'], name='gyms_is_acti_07dba4_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['name'], name='gyms_name_4e91a3_idx'),
        ),
        migrations.AddField(
            model_name='basetimeslot',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_slots', to='app.gym'),
        ),
        migrations.AddField(
            model_name='dailytimeslot',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='app.gym'),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.gym'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.gym'),
        ),
        migrations.AddField(
            model_name='timeslotsignup',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.gym'),
        ),
        migrations.AddField(
            model_name='userweight',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='app.gym'),
        ),
        migrations.AddIndex(
            model_name='basetimeslot',
            index=models.Index(fields=['gym', 'is_active'], name='base_timesl_gym_id_b4d252_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimeslot',
            index=models.Index(fields=['gym', 'slot_date'], name='daily_times_gym_id_fbdaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimeslot',
            index=models.Index(fields=['gym', 'status'], name='daily_times_gym_id_b759a2_idx'),
        ),
        migrations.AddIndex(
            model_name='gymuser',
            index=models.Index(fields=['gym', 'is_active'], name='users_gym_id_568227_idx'),
        ),
        migrations.AddIndex(
            model_name='gymuser',
            index=models.Index(fields=['gym', 'join_date'], name='users_gym_id_1f0a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='gymuser',
            index=models.Index(fields=['gym', 'phone'], name='users_gym_id_c238dc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym', 'user', 'period_start', 'period_end'], name='idx_pay_gym_user_period'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym', 'paid_at'], name='payments_gym_id_7758f8_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslotsignup',
            index=models.Index(fields=['gym', 'user', 'slot_date'], name='idx_signup_gym_user_date'),
        ),
        migrations.AddIndex(
            model_name='userweight',
            index=models.Index(fields=['gym', 'user', 'recorded_at'], name='user_weight_gym_id_ff1762_idx'),
        ),
        migrations.AddConstraint(
            model_name='basetimeslot',
            constraint=models.UniqueConstraint(fields=('gym', 'title'), name='uniq_base_title_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='dailytimeslot',
            constraint=models.UniqueConstraint(fields=('gym', 'slot_date', 'title'), name='uniq_daily_date_title_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='timeslotsignup',
            constraint=models.UniqueConstraint(fields=('gym', 'user', 'slot_date'), name='uniq_signup_user_day_per_gym'),
        ),
    ]
