# Generated by Django 5.0.1 on 2026-02-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_measurementvalue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='measurementdefinition',
            name='code',
            field=models.CharField(blank=True, choices=[('weight', 'Weight'), ('waist', 'Waist circumference'), ('hip', 'Hip circumference'), ('neck', 'Neck circumference'), ('body_fat_percent', 'Body fat %'), ('fat_mass', 'Fat mass'), ('lean_mass', 'Lean mass'), ('muscle_mass', 'Muscle mass'), ('bmi', 'Body Mass Index'), ('whr', 'Waist-Hip Ratio'), ('whtr', 'Waist-Height Ratio'), ('bmr', 'Basal Metabolic Rate'), ('tdee', 'Total Daily Energy Expenditure'), ('water_percent', 'Body water %')], max_length=40, null=True, unique=True),
        ),
    ]
