# Generated by Django 5.0.1 on 2026-02-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_gymuser_sex_measurementdefinition_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementvalue',
            name='definition_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
