# Generated by Django 5.0.1 on 2025-11-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_backfill_gym_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetimeslot',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_slots', to='app.gym'),
        ),
        migrations.AlterField(
            model_name='dailytimeslot',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='app.gym'),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.gym'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.gym'),
        ),
        migrations.AlterField(
            model_name='timeslotsignup',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.gym'),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='app.gym'),
        ),
    ]
