# Generated by Django 5.0.1 on 2026-02-02 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_measurementvalue_definition_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
