# Generated by Django 5.0.1 on 2025-11-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_basetimeslot_gym_alter_dailytimeslot_gym_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basetimeslot',
            options={'ordering': ['day_order']},
        ),
        migrations.AlterModelOptions(
            name='dailytimeslot',
            options={'ordering': ['day_order']},
        ),
        migrations.AddField(
            model_name='basetimeslot',
            name='day_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytimeslot',
            name='day_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='basetimeslot',
            index=models.Index(fields=['day_order'], name='base_timesl_day_ord_a169a0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimeslot',
            index=models.Index(fields=['day_order'], name='daily_times_day_ord_3a7b4a_idx'),
        ),
    ]
