# Generated by Django 5.0.1 on 2026-02-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_gymuser_height_cm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True),
        ),
    ]
