# Generated by Django 5.0.1 on 2026-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_gymuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementdefinition',
            name='code',
            field=models.CharField(blank=True, choices=[('weight', 'Peso'), ('waist', 'Cintura'), ('hip', 'Cadera'), ('neck', 'Cuello'), ('body_fat_percent', 'Grasa corporal'), ('fat_mass', 'Masa grasa'), ('lean_mass', 'Masa magra'), ('muscle_mass', 'Masa muscular'), ('bmi', 'Índice de masa corporal'), ('whr', 'Relación cintura-cadera'), ('whtr', 'Relación cintura-estatura'), ('bmr', 'Tasa metabólica basal'), ('tdee', 'Gasto energético diario total'), ('water_percent', 'Porcentaje de agua corporal')], max_length=40, null=True, unique=True),
        ),
    ]
