# Generated by Django 5.0.1 on 2026-02-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_measurementdefinition_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementvalue',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
