# Generated by Django 5.0.1 on 2026-02-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_measurementvalue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementvalue',
            name='name',
        ),
    ]
